<?php
/**
 * 验证
 * Date: 2018/12/3
 * Time: 12:24
 */

namespace App\Http\Wechat\Action\Oauth;

use Wechat\Action\BaseAction;

class AdminAction extends BaseAction
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}