<?php
/**
 * 用户列表
 * Date: 2018/12/9
 * Time: 17:42
 */
namespace App\Http\Admin\Action\User;

use Admin\Action\BaseAction;

class IndexAction extends BaseAction
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}