<?php
/**
 *
 * Date: 2018/12/15
 * Time: 23:24
 */
namespace App\Http\Admin\Action\User\apply;

use Admin\Action\BaseAction;

class IndexAction extends BaseAction
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}