<?php
/**
 * 微信服务操作
 * Date: 2018/12/3
 * Time: 12:21
 */
namespace App\Http\Wechat\Action\Wechat;

use Wechat\Action\BaseAction;

class ServiceAction extends BaseAction
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}