<?php
/**
 * 文章管理中心
 * Date: 2018/12/9
 * Time: 17:43
 */
namespace App\Http\Admin\Action\Spread\Article;

use Admin\Action\BaseAction;

class IndexAction extends BaseAction
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}