<?php
/**
 * 管理员自定义权限
 * Date: 2018/12/4
 * Time: 17:52
 */
namespace Admin\Services\Authority\Integration;

use Frameworks\Services\Basic\Processor\BaseWorkProcessor;

class OwnerCustomAuthorityIntegration extends BaseWorkProcessor
{
    protected $owner = null;
    protected $role = null;
    protected $checkList = [];

    public function __construct($owner = null, $checkList = [])
    {
        $this->_init($owner, $checkList);
    }

    public function _init($owner, $checkList = [])
    {
        $this->owner = $owner;
        $this->checkList = $checkList;
        if (isset($owner->role)) {

        }
        return $this;
    }

    protected function parseList()
    {

    }

    public function process()
    {
        parent::process(); // TODO: Change the autogenerated stub
    }

}