<?php
/**
 * 作废专业
 * Date: 2018/12/10
 * Time: 8:59
 */
namespace App\Http\Admin\Action\Cultivate\Major;

use Admin\Action\BaseAction;
use Frameworks\Traits\ApiActionTrait;

class RemoveAction extends BaseAction
{
    use ApiActionTrait;

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}