<?php
/**
 * 交易订单列表
 * Date: 2018/12/5
 * Time: 17:05
 */
namespace App\Http\Admin\Action\Trade\Order;

use Admin\Action\BaseAction;

class IndexAction extends BaseAction
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}