<?php
/**
 * 登录验证
 * Date: 2018/12/1
 * Time: 18:01
 */
namespace App\Http\Admin\Action\Basic;

use Admin\Action\BaseAction;

class CheckAction extends BaseAction
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}