<?php
/**
 * 登录
 * Date: 2018/12/1
 * Time: 18:00
 */
namespace App\Http\Admin\Action\Basic;

use Admin\Action\BaseAction;

class LoginAction extends BaseAction
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}