<?php
/**
 * 首页
 * Date: 2018/12/1
 * Time: 18:10
 */
namespace App\Http\Admin\Action\Basic;

use Admin\Action\BaseAction;

class ReplyAction extends BaseAction
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}