<?php
/**
 * 系统登录跳转首页
 * Date: 2018/12/3
 * Time: 10:26
 */
namespace App\Http\Admin\Action\System;

use Admin\Action\BaseAction;

class IndexAction extends BaseAction
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}
