<?php
/**
 * 业务日志
 * Date: 2018/12/3
 * Time: 15:10
 */
namespace App\Http\Admin\Action\System\Log;

use Admin\Action\BaseAction;

class IndexOperateAction extends BaseAction
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}